window.log=function f(){log.history=log.history||[];log.history.push(arguments);if(this.console){var a=arguments;try{a.callee=f.caller}catch(d){}a=[].slice.call(a);typeof console.log==="object"?log.apply.call(console.log,console,a):console.log.apply(console,a)}};
(function(b){function a(){}for(var d="assert,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,markTimeline,profile,profileEnd,time,timeEnd,trace,warn".split(","),c;c=d.pop();)b[c]=b[c]||a})(function(){try{return console.log(),window.console}catch(b){return window.console={}}}());
(function(c){var e=function(a,b){this.init("tooltip",a,b)};e.prototype={constructor:e,init:function(a,b,d){this.type=a;this.$element=c(b);this.options=this.getOptions(d);this.enabled=!0;this.options.trigger!="manual"&&(a=this.options.trigger=="hover"?"mouseenter":"focus",b=this.options.trigger=="hover"?"mouseleave":"blur",this.$element.on(a,this.options.selector,c.proxy(this.enter,this)),this.$element.on(b,this.options.selector,c.proxy(this.leave,this)));this.options.selector?this._options=c.extend({},
this.options,{trigger:"manual",selector:""}):this.fixTitle()},getOptions:function(a){a=c.extend({},c.fn[this.type].defaults,a,this.$element.data());if(a.delay&&typeof a.delay=="number")a.delay={show:a.delay,hide:a.delay};return a},enter:function(a){var b=c(a.currentTarget)[this.type](this._options).data(this.type);if(!b.options.delay||!b.options.delay.show)return b.show();clearTimeout(this.timeout);b.hoverState="in";this.timeout=setTimeout(function(){b.hoverState=="in"&&b.show()},b.options.delay.show)},
leave:function(a){var b=c(a.currentTarget)[this.type](this._options).data(this.type);if(!b.options.delay||!b.options.delay.hide)return b.hide();clearTimeout(this.timeout);b.hoverState="out";this.timeout=setTimeout(function(){b.hoverState=="out"&&b.hide()},b.options.delay.hide)},show:function(){var a,b,d,c,e,f,g;if(this.hasContent()&&this.enabled){a=this.tip();this.setContent();this.options.animation&&a.addClass("fade");f=typeof this.options.placement=="function"?this.options.placement.call(this,a[0],
this.$element[0]):this.options.placement;b=/in/.test(f);a.remove().css({top:0,left:0,display:"block"}).appendTo(b?this.$element:document.body);d=this.getPosition(b);c=a[0].offsetWidth;e=a[0].offsetHeight;switch(b?f.split(" ")[1]:f){case "bottom":g={top:d.top+d.height,left:d.left+d.width/2-c/2};break;case "top":g={top:d.top-e,left:d.left+d.width/2-c/2};break;case "left":g={top:d.top+d.height/2-e/2,left:d.left-c};break;case "right":g={top:d.top+d.height/2-e/2,left:d.left+d.width}}a.css(g).addClass(f).addClass("in")}},
isHTML:function(a){return typeof a!="string"||a.charAt(0)==="<"&&a.charAt(a.length-1)===">"&&a.length>=3||/^(?:[^<]*<[\w\W]+>[^>]*$)/.exec(a)},setContent:function(){var a=this.tip(),b=this.getTitle();a.find(".tooltip-inner")[this.isHTML(b)?"html":"text"](b);a.removeClass("fade in top bottom left right")},hide:function(){function a(){var a=setTimeout(function(){b.off(c.support.transition.end).remove()},500);b.one(c.support.transition.end,function(){clearTimeout(a);b.remove()})}var b=this.tip();b.removeClass("in");
c.support.transition&&this.$tip.hasClass("fade")?a():b.remove()},fixTitle:function(){var a=this.$element;if(a.attr("title")||typeof a.attr("data-original-title")!="string")a.attr("data-original-title",a.attr("title")||"").removeAttr("title")},hasContent:function(){return this.getTitle()},getPosition:function(a){return c.extend({},a?{top:0,left:0}:this.$element.offset(),{width:this.$element[0].offsetWidth,height:this.$element[0].offsetHeight})},getTitle:function(){var a=this.$element,b=this.options;
return a.attr("data-original-title")||(typeof b.title=="function"?b.title.call(a[0]):b.title)},tip:function(){return this.$tip=this.$tip||c(this.options.template)},validate:function(){if(!this.$element[0].parentNode)this.hide(),this.options=this.$element=null},enable:function(){this.enabled=!0},disable:function(){this.enabled=!1},toggleEnabled:function(){this.enabled=!this.enabled},toggle:function(){this[this.tip().hasClass("in")?"hide":"show"]()}};c.fn.tooltip=function(a){return this.each(function(){var b=
c(this),d=b.data("tooltip"),h=typeof a=="object"&&a;d||b.data("tooltip",d=new e(this,h));if(typeof a=="string")d[a]()})};c.fn.tooltip.Constructor=e;c.fn.tooltip.defaults={animation:!0,placement:"top",selector:!1,template:'<div class="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',trigger:"hover",title:"",delay:0}})(window.jQuery);
(function(a){var g=function(b){a(b).on("click",'[data-dismiss="alert"]',this.close)};g.prototype.close=function(b){function e(){d.trigger("closed").remove()}var c=a(this),f=c.attr("data-target"),d;f||(f=(f=c.attr("href"))&&f.replace(/.*(?=#[^\s]*$)/,""));d=a(f);b&&b.preventDefault();d.length||(d=c.hasClass("alert")?c:c.parent());d.trigger(b=a.Event("close"));b.isDefaultPrevented()||(d.removeClass("in"),a.support.transition&&d.hasClass("fade")?d.on(a.support.transition.end,e):e())};a.fn.alert=function(b){return this.each(function(){var e=
a(this),c=e.data("alert");c||e.data("alert",c=new g(this));typeof b=="string"&&c[b].call(e)})};a.fn.alert.Constructor=g;a(function(){a("body").on("click.alert.data-api",'[data-dismiss="alert"]',g.prototype.close)})})(window.jQuery);
(function(b){var d=function(a,c){this.$element=b(a);this.options=b.extend({},b.fn.button.defaults,c)};d.prototype.setState=function(a){var c=this.$element,b=c.data(),d=c.is("input")?"val":"html";a+="Text";b.resetText||c.data("resetText",c[d]());c[d](b[a]||this.options[a]);setTimeout(function(){a=="loadingText"?c.addClass("disabled").attr("disabled","disabled"):c.removeClass("disabled").removeAttr("disabled")},0)};d.prototype.toggle=function(){var a=this.$element.parent('[data-toggle="buttons-radio"]');
a&&a.find(".active").removeClass("active");this.$element.toggleClass("active")};b.fn.button=function(a){return this.each(function(){var c=b(this),e=c.data("button"),f=typeof a=="object"&&a;e||c.data("button",e=new d(this,f));a=="toggle"?e.toggle():a&&e.setState(a)})};b.fn.button.defaults={loadingText:"loading..."};b.fn.button.Constructor=d;b(function(){b("body").on("click.button.data-api","[data-toggle^=button]",function(a){a=b(a.target);a.hasClass("btn")||(a=a.closest(".btn"));a.button("toggle")})})})(window.jQuery);
(function(b){var f=function(a,c){this.$element=b(a);this.options=c;this.options.slide&&this.slide(this.options.slide);this.options.pause=="hover"&&this.$element.on("mouseenter",b.proxy(this.pause,this)).on("mouseleave",b.proxy(this.cycle,this))};f.prototype={cycle:function(a){if(!a)this.paused=!1;this.options.interval&&!this.paused&&(this.interval=setInterval(b.proxy(this.next,this),this.options.interval));return this},to:function(a){var c=this.$element.find(".active"),e=c.parent().children(),c=e.index(c),
d=this;if(!(a>e.length-1||a<0))return this.sliding?this.$element.one("slid",function(){d.to(a)}):c==a?this.pause().cycle():this.slide(a>c?"next":"prev",b(e[a]))},pause:function(a){if(!a)this.paused=!0;clearInterval(this.interval);this.interval=null;return this},next:function(){return this.sliding?void 0:this.slide("next")},prev:function(){return this.sliding?void 0:this.slide("prev")},slide:function(a,c){var e=this.$element.find(".active"),d=c||e[a](),f=this.interval,g=a=="next"?"left":"right",j=
a=="next"?"first":"last",i=this,h=b.Event("slide");this.sliding=!0;f&&this.pause();d=d.length?d:this.$element.find(".item")[j]();if(!d.hasClass("active")){if(b.support.transition&&this.$element.hasClass("slide")){this.$element.trigger(h);if(h.isDefaultPrevented())return;d.addClass(a);e.addClass(g);d.addClass(g);this.$element.one(b.support.transition.end,function(){d.removeClass([a,g].join(" ")).addClass("active");e.removeClass(["active",g].join(" "));i.sliding=!1;setTimeout(function(){i.$element.trigger("slid")},
0)})}else{this.$element.trigger(h);if(h.isDefaultPrevented())return;e.removeClass("active");d.addClass("active");this.sliding=!1;this.$element.trigger("slid")}f&&this.cycle();return this}}};b.fn.carousel=function(a){return this.each(function(){var c=b(this),e=c.data("carousel"),d=b.extend({},b.fn.carousel.defaults,typeof a=="object"&&a);e||c.data("carousel",e=new f(this,d));if(typeof a=="number")e.to(a);else if(typeof a=="string"||(a=d.slide))e[a]();else d.interval&&e.cycle()})};b.fn.carousel.defaults=
{interval:5E3,pause:"hover"};b.fn.carousel.Constructor=f;b(function(){b("body").on("click.carousel.data-api","[data-slide]",function(a){var c=b(this),e,d=b(c.attr("data-target")||(e=c.attr("href"))&&e.replace(/.*(?=#[^\s]+$)/,"")),c=!d.data("modal")&&b.extend({},d.data(),c.data());d.carousel(c);a.preventDefault()})})})(window.jQuery);
(function(c){var f=function(a,b){this.$element=c(a);this.options=c.extend({},c.fn.collapse.defaults,b);if(this.options.parent)this.$parent=c(this.options.parent);this.options.toggle&&this.toggle()};f.prototype={constructor:f,dimension:function(){return this.$element.hasClass("width")?"width":"height"},show:function(){var a,b,d,e;if(!this.transitioning){a=this.dimension();b=c.camelCase(["scroll",a].join("-"));if((d=this.$parent&&this.$parent.find("> .accordion-group > .in"))&&d.length){if((e=d.data("collapse"))&&
e.transitioning)return;d.collapse("hide");e||d.data("collapse",null)}this.$element[a](0);this.transition("addClass",c.Event("show"),"shown");this.$element[a](this.$element[0][b])}},hide:function(){var a;this.transitioning||(a=this.dimension(),this.reset(this.$element[a]()),this.transition("removeClass",c.Event("hide"),"hidden"),this.$element[a](0))},reset:function(a){var b=this.dimension();this.$element.removeClass("collapse")[b](a||"auto");this.$element[a!==null?"addClass":"removeClass"]("collapse");
return this},transition:function(a,b,d){var e=this,f=function(){b=="show"&&e.reset();e.transitioning=0;e.$element.trigger(d)};this.$element.trigger(b);if(!b.isDefaultPrevented())this.transitioning=1,this.$element[a]("in"),c.support.transition&&this.$element.hasClass("collapse")?this.$element.one(c.support.transition.end,f):f()},toggle:function(){this[this.$element.hasClass("in")?"hide":"show"]()}};c.fn.collapse=function(a){return this.each(function(){var b=c(this),d=b.data("collapse"),e=typeof a==
"object"&&a;d||b.data("collapse",d=new f(this,e));if(typeof a=="string")d[a]()})};c.fn.collapse.defaults={toggle:!0};c.fn.collapse.Constructor=f;c(function(){c("body").on("click.collapse.data-api","[data-toggle=collapse]",function(a){var b=c(this),d,a=b.attr("data-target")||a.preventDefault()||(d=b.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,""),b=c(a).data("collapse")?"toggle":b.data();c(a).collapse(b)})})})(window.jQuery);
(function(c){function f(){c(g).parent().removeClass("open")}var g='[data-toggle="dropdown"]',d=function(b){var a=c(b).on("click.dropdown.data-api",this.toggle);c("html").on("click.dropdown.data-api",function(){a.parent().removeClass("open")})};d.prototype={constructor:d,toggle:function(){var b=c(this),a;if(!b.is(".disabled, :disabled"))return a=b.attr("data-target"),a||(a=(a=b.attr("href"))&&a.replace(/.*(?=#[^\s]*$)/,"")),a=c(a),a.length||(a=b.parent()),b=a.hasClass("open"),f(),b||a.toggleClass("open"),
!1}};c.fn.dropdown=function(b){return this.each(function(){var a=c(this),e=a.data("dropdown");e||a.data("dropdown",e=new d(this));typeof b=="string"&&e[b].call(a)})};c.fn.dropdown.Constructor=d;c(function(){c("html").on("click.dropdown.data-api",f);c("body").on("click.dropdown",".dropdown form",function(b){b.stopPropagation()}).on("click.dropdown.data-api",g,d.prototype.toggle)})})(window.jQuery);
(function(b){function k(){var a=this,c=setTimeout(function(){a.$element.off(b.support.transition.end);g.call(a)},500);this.$element.one(b.support.transition.end,function(){clearTimeout(c);g.call(a)})}function g(){this.$element.hide().trigger("hidden");h.call(this)}function h(a){var c=this.$element.hasClass("fade")?"fade":"";if(this.isShown&&this.options.backdrop){var d=b.support.transition&&c;this.$backdrop=b('<div class="modal-backdrop '+c+'" />').appendTo(document.body);this.options.backdrop!="static"&&
this.$backdrop.click(b.proxy(this.hide,this));this.$backdrop.addClass("in");d?this.$backdrop.one(b.support.transition.end,a):a()}else!this.isShown&&this.$backdrop?(this.$backdrop.removeClass("in"),b.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one(b.support.transition.end,b.proxy(i,this)):i.call(this)):a&&a()}function i(){this.$backdrop.remove();this.$backdrop=null}function j(){var a=this;if(this.isShown&&this.options.keyboard)b(document).on("keyup.dismiss.modal",function(b){b.which==
27&&a.hide()});else this.isShown||b(document).off("keyup.dismiss.modal")}var f=function(a,c){this.options=c;this.$element=b(a).delegate('[data-dismiss="modal"]',"click.dismiss.modal",b.proxy(this.hide,this))};f.prototype={constructor:f,toggle:function(){return this[!this.isShown?"show":"hide"]()},show:function(){var a=this,c=b.Event("show");this.$element.trigger(c);if(!this.isShown&&!c.isDefaultPrevented())b("body").addClass("modal-open"),this.isShown=!0,j.call(this),h.call(this,function(){var c=
b.support.transition&&a.$element.hasClass("fade");a.$element.parent().length||a.$element.appendTo(document.body);a.$element.show();a.$element.addClass("in");c?a.$element.one(b.support.transition.end,function(){a.$element.trigger("shown")}):a.$element.trigger("shown")})},hide:function(a){a&&a.preventDefault();a=b.Event("hide");this.$element.trigger(a);if(this.isShown&&!a.isDefaultPrevented())this.isShown=!1,b("body").removeClass("modal-open"),j.call(this),this.$element.removeClass("in"),b.support.transition&&
this.$element.hasClass("fade")?k.call(this):g.call(this)}};b.fn.modal=function(a){return this.each(function(){var c=b(this),d=c.data("modal"),e=b.extend({},b.fn.modal.defaults,c.data(),typeof a=="object"&&a);d||c.data("modal",d=new f(this,e));if(typeof a=="string")d[a]();else e.show&&d.show()})};b.fn.modal.defaults={backdrop:!0,keyboard:!0,show:!0};b.fn.modal.Constructor=f;b(function(){b("body").on("click.modal.data-api",'[data-toggle="modal"]',function(a){var c=b(this),d,e=b(c.attr("data-target")||
(d=c.attr("href"))&&d.replace(/.*(?=#[^\s]+$)/,"")),c=e.data("modal")?"toggle":b.extend({},e.data(),c.data());a.preventDefault();e.modal(c)})})})(window.jQuery);
(function(a){var d=function(b,c){this.init("popover",b,c)};d.prototype=a.extend({},a.fn.tooltip.Constructor.prototype,{constructor:d,setContent:function(){var b=this.tip(),c=this.getTitle(),a=this.getContent();b.find(".popover-title")[this.isHTML(c)?"html":"text"](c);b.find(".popover-content > *")[this.isHTML(a)?"html":"text"](a);b.removeClass("fade top bottom left right in")},hasContent:function(){return this.getTitle()||this.getContent()},getContent:function(){var b=this.$element,a=this.options;
return b.attr("data-content")||(typeof a.content=="function"?a.content.call(b[0]):a.content)},tip:function(){if(!this.$tip)this.$tip=a(this.options.template);return this.$tip}});a.fn.popover=function(b){return this.each(function(){var c=a(this),e=c.data("popover"),f=typeof b=="object"&&b;e||c.data("popover",e=new d(this,f));if(typeof b=="string")e[b]()})};a.fn.popover.Constructor=d;a.fn.popover.defaults=a.extend({},a.fn.tooltip.defaults,{placement:"right",content:"",template:'<div class="popover"><div class="arrow"></div><div class="popover-inner"><h3 class="popover-title"></h3><div class="popover-content"><p></p></div></div></div>'})})(window.jQuery);
(function(b){function g(a,h){var c=b.proxy(this.process,this),e=b(a).is("body")?b(window):b(a),f;this.options=b.extend({},b.fn.scrollspy.defaults,h);this.$scrollElement=e.on("scroll.scroll.data-api",c);this.selector=(this.options.target||(f=b(a).attr("href"))&&f.replace(/.*(?=#[^\s]+$)/,"")||"")+" .nav li > a";this.$body=b("body").on("click.scroll.data-api",this.selector,c);this.refresh();this.process()}g.prototype={constructor:g,refresh:function(){var a=this;this.offsets=b([]);this.targets=b([]);
this.$body.find(this.selector).map(function(){var a=b(this),a=a.data("target")||a.attr("href"),c=/^#\w/.test(a)&&b(a);return c&&a.length&&[[c.position().top,a]]||null}).sort(function(a,b){return a[0]-b[0]}).each(function(){a.offsets.push(this[0]);a.targets.push(this[1])})},process:function(){var a=this.$scrollElement.scrollTop()+this.options.offset,b=(this.$scrollElement[0].scrollHeight||this.$body[0].scrollHeight)-this.$scrollElement.height(),c=this.offsets,e=this.targets,f=this.activeTarget,d;if(a>=
b)return f!=(d=e.last()[0])&&this.activate(d);for(d=c.length;d--;)f!=e[d]&&a>=c[d]&&(!c[d+1]||a<=c[d+1])&&this.activate(e[d])},activate:function(a){this.activeTarget=a;b(this.selector).parent(".active").removeClass("active");a=b(this.selector+'[data-target="'+a+'"],'+this.selector+'[href="'+a+'"]').parent("li").addClass("active");a.parent(".dropdown-menu")&&(a=a.closest("li.dropdown").addClass("active"));a.trigger("activate")}};b.fn.scrollspy=function(a){return this.each(function(){var h=b(this),
c=h.data("scrollspy"),e=typeof a=="object"&&a;c||h.data("scrollspy",c=new g(this,e));if(typeof a=="string")c[a]()})};b.fn.scrollspy.Constructor=g;b.fn.scrollspy.defaults={offset:10};b(function(){b('[data-spy="scroll"]').each(function(){var a=b(this);a.scrollspy(a.data())})})})(window.jQuery);
(function(c){var e=function(a){this.element=c(a)};e.prototype={constructor:e,show:function(){var a=this.element,f=a.closest("ul:not(.dropdown-menu)"),b=a.attr("data-target"),g,d;b||(b=(b=a.attr("href"))&&b.replace(/.*(?=#[^\s]*$)/,""));a.parent("li").hasClass("active")||(g=f.find(".active a").last()[0],d=c.Event("show",{relatedTarget:g}),a.trigger(d),d.isDefaultPrevented()||(b=c(b),this.activate(a.parent("li"),f),this.activate(b,b.parent(),function(){a.trigger({type:"shown",relatedTarget:g})})))},
activate:function(a,f,b){function g(){d.removeClass("active").find("> .dropdown-menu > .active").removeClass("active");a.addClass("active");e?a.addClass("in"):a.removeClass("fade");a.parent(".dropdown-menu")&&a.closest("li.dropdown").addClass("active");b&&b()}var d=f.find("> .active"),e=b&&c.support.transition&&d.hasClass("fade");e?d.one(c.support.transition.end,g):g();d.removeClass("in")}};c.fn.tab=function(a){return this.each(function(){var f=c(this),b=f.data("tab");b||f.data("tab",b=new e(this));
if(typeof a=="string")b[a]()})};c.fn.tab.Constructor=e;c(function(){c("body").on("click.tab.data-api",'[data-toggle="tab"], [data-toggle="pill"]',function(a){a.preventDefault();c(this).tab("show")})})})(window.jQuery);
(function(a){a(function(){a.support.transition=function(){var a=function(){var a=document.createElement("bootstrap"),c={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd",msTransition:"MSTransitionEnd",transition:"transitionend"},b;for(b in c)if(a.style[b]!==void 0)return c[b]}();return a&&{end:a}}()})})(window.jQuery);
(function(b){var g=function(a,c){this.$element=b(a);this.options=b.extend({},b.fn.typeahead.defaults,c);this.matcher=this.options.matcher||this.matcher;this.sorter=this.options.sorter||this.sorter;this.highlighter=this.options.highlighter||this.highlighter;this.updater=this.options.updater||this.updater;this.$menu=b(this.options.menu).appendTo("body");this.source=this.options.source;this.shown=!1;this.listen()};g.prototype={constructor:g,select:function(){this.$element.val(this.updater(this.$menu.find(".active").attr("data-value"))).change();
return this.hide()},updater:function(a){return a},show:function(){var a=b.extend({},this.$element.position(),{height:this.$element[0].offsetHeight});this.$menu.css({top:a.top+a.height,left:a.left});this.$menu.show();this.shown=!0;return this},hide:function(){this.$menu.hide();this.shown=!1;return this},lookup:function(){var a=this,c;this.query=this.$element.val();if(!this.query)return this.shown?this.hide():this;c=b.grep(this.source,function(b){return a.matcher(b)});c=this.sorter(c);return!c.length?
this.shown?this.hide():this:this.render(c.slice(0,this.options.items)).show()},matcher:function(a){return~a.toLowerCase().indexOf(this.query.toLowerCase())},sorter:function(a){for(var b=[],e=[],d=[],f;f=a.shift();)f.toLowerCase().indexOf(this.query.toLowerCase())?~f.indexOf(this.query)?e.push(f):d.push(f):b.push(f);return b.concat(e,d)},highlighter:function(a){var b=this.query.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&");return a.replace(RegExp("("+b+")","ig"),function(a,b){return"<strong>"+b+"</strong>"})},
render:function(a){var c=this,a=b(a).map(function(a,d){a=b(c.options.item).attr("data-value",d);a.find("a").html(c.highlighter(d));return a[0]});a.first().addClass("active");this.$menu.html(a);return this},next:function(){var a=this.$menu.find(".active").removeClass("active").next();a.length||(a=b(this.$menu.find("li")[0]));a.addClass("active")},prev:function(){var a=this.$menu.find(".active").removeClass("active").prev();a.length||(a=this.$menu.find("li").last());a.addClass("active")},listen:function(){this.$element.on("blur",
b.proxy(this.blur,this)).on("keypress",b.proxy(this.keypress,this)).on("keyup",b.proxy(this.keyup,this));if(b.browser.webkit||b.browser.msie)this.$element.on("keydown",b.proxy(this.keypress,this));this.$menu.on("click",b.proxy(this.click,this)).on("mouseenter","li",b.proxy(this.mouseenter,this))},keyup:function(a){switch(a.keyCode){case 40:case 38:break;case 9:case 13:if(!this.shown)return;this.select();break;case 27:if(!this.shown)return;this.hide();break;default:this.lookup()}a.stopPropagation();
a.preventDefault()},keypress:function(a){if(this.shown){switch(a.keyCode){case 9:case 13:case 27:a.preventDefault();break;case 38:if(a.type!="keydown")break;a.preventDefault();this.prev();break;case 40:if(a.type!="keydown")break;a.preventDefault();this.next()}a.stopPropagation()}},blur:function(){var a=this;setTimeout(function(){a.hide()},150)},click:function(a){a.stopPropagation();a.preventDefault();this.select()},mouseenter:function(a){this.$menu.find(".active").removeClass("active");b(a.currentTarget).addClass("active")}};
b.fn.typeahead=function(a){return this.each(function(){var c=b(this),e=c.data("typeahead"),d=typeof a=="object"&&a;e||c.data("typeahead",e=new g(this,d));if(typeof a=="string")e[a]()})};b.fn.typeahead.defaults={source:[],items:8,menu:'<ul class="typeahead dropdown-menu"></ul>',item:'<li><a href="#"></a></li>'};b.fn.typeahead.Constructor=g;b(function(){b("body").on("focus.typeahead.data-api",'[data-provide="typeahead"]',function(a){var c=b(this);c.data("typeahead")||(a.preventDefault(),c.typeahead(c.data()))})})})(window.jQuery);
window.log=function f(){log.history=log.history||[];log.history.push(arguments);if(this.console){var a=arguments;try{a.callee=f.caller}catch(d){}a=[].slice.call(a);typeof console.log==="object"?log.apply.call(console.log,console,a):console.log.apply(console,a)}};
(function(b){function a(){}for(var d="assert,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,markTimeline,profile,profileEnd,time,timeEnd,trace,warn".split(","),c;c=d.pop();)b[c]=b[c]||a})(function(){try{return console.log(),window.console}catch(b){return window.console={}}}());
