version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: US/Central
  open-pull-requests-limit: 10
  target-branch: main
  ignore:
  - dependency-name: filp/whoops
    versions:
    - 2.10.0
    - 2.11.0
    - 2.12.0
    - 2.9.2
  - dependency-name: symfony/http-kernel
    versions:
    - 5.2.2
    - 5.2.3
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: US/Central
  open-pull-requests-limit: 10
  target-branch: main
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: laravel-mix
    versions:
    - 5.0.9
    - 6.0.13
    - 6.0.16
    - 6.0.17
  - dependency-name: sass
    versions:
    - 1.32.10
    - 1.32.11
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@wordpress/browserslist-config"
    versions:
    - 3.0.2
  - dependency-name: "@wordpress/babel-preset-default"
    versions:
    - 5.0.0
    - 5.0.1
    - 5.1.0
    - 5.2.0
  - dependency-name: "@wordpress/dependency-extraction-webpack-plugin"
    versions:
    - 3.1.0
    - 3.1.1
  - dependency-name: tailwindcss
    versions:
    - 2.0.4
    - 2.1.1
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
    - 13.9.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
    - 11.0.1
  - dependency-name: browser-sync
    versions:
    - 2.26.14
  - dependency-name: purgecss-with-wordpress
    versions:
    - 4.0.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: vue-template-compiler
    versions:
    - 2.6.12
  - dependency-name: eslint-plugin-import
    versions:
    - 2.22.1
