<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_brand-details',
		'title' => 'Brand - Details',
		'fields' => array (
			array (
				'key' => 'field_7',
				'label' => 'Brand Website',
				'name' => 'brand_website',
				'type' => 'text',
				'instructions' => 'example: http://unistrut.com',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5238f3bc143b9',
				'label' => 'Brand RSS Feed',
				'name' => 'brand_rss_feed',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_8',
				'label' => 'Brand Description',
				'name' => 'brand_description',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_51f574e8795cf',
				'label' => 'Brand Logo Color',
				'name' => 'brand_logo_color',
				'type' => 'image',
				'save_format' => 'ID',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_52678e1dec577',
				'label' => 'Brand Logo Gray',
				'name' => 'brand_logo_gray',
				'type' => 'image',
				'save_format' => 'ID',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_51f57520795d0',
				'label' => 'Brand Logo Black',
				'name' => 'brand_logo_black',
				'type' => 'image',
				'save_format' => 'ID',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_51f5752d795d1',
				'label' => 'Brand Logo White',
				'name' => 'brand_logo_white',
				'type' => 'image',
				'save_format' => 'ID',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5238f349143b8',
				'label' => 'Include in Footer?',
				'name' => 'include_in_footer',
				'type' => 'true_false',
				'instructions' => 'Should this brand be visible in the footer carousel?',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_51f5755b3a6c9',
				'label' => 'Primary Color',
				'name' => 'primary_color',
				'type' => 'color_picker',
				'default_value' => '',
			),
			array (
				'key' => 'field_51f575733a6ca',
				'label' => 'Secondary Color',
				'name' => 'secondary_color',
				'type' => 'color_picker',
				'default_value' => '',
			),
			array (
				'key' => 'field_51f575833a6cb',
				'label' => 'Tertiary Color',
				'name' => 'tertiary_color',
				'type' => 'color_picker',
				'default_value' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'brand',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
