<?php 

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_options-branding',
		'title' => 'Options - Branding',
		'fields' => array (
			array (
				'key' => 'field_517f918cc86dc',
				'label' => 'Logos',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_522480b139cfd',
				'label' => 'Base 64 Alts?',
				'name' => 'base_64_alts',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_517f912ac86d9',
				'label' => 'Color Logo',
				'name' => 'color_logo',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_522480cc39cfe',
				'label' => 'Color Logo Base64',
				'name' => 'color_logo_base64',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_522480b139cfd',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5202e1958578f',
				'label' => 'Color Logo no Atkore',
				'name' => 'color_logo_no_atkore',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_522480f439cff',
				'label' => 'Color Logo no Atkore Base64',
				'name' => 'color_logo_no_atkore_base64',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_522480b139cfd',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_51ff11e4b7038',
				'label' => 'Color Logo Horizontal',
				'name' => 'color_logo_horizontal',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_5224811039d00',
				'label' => 'Color Logo Horizontal Base64',
				'name' => 'color_logo_horizontal_base64',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_522480b139cfd',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5202da3a1b28c',
				'label' => 'White Logo',
				'name' => 'white_logo',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_5224813c39d01',
				'label' => 'White Logo Base64',
				'name' => 'white_logo_base64',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_522480b139cfd',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5202e1b185790',
				'label' => 'White Logo no Atkore',
				'name' => 'white_logo_no_atkore',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_5224814d39d02',
				'label' => 'White Logo no Atkore Base64',
				'name' => 'white_logo_no_atkore_base64',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_522480b139cfd',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_51ff1204b7039',
				'label' => 'White Logo Horizontal',
				'name' => 'white_logo_horizontal',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_5224817139d03',
				'label' => 'White Logo Horizontal Base64',
				'name' => 'white_logo_horizontal_base64',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_522480b139cfd',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_517f9175c86db',
				'label' => 'Black Logo',
				'name' => 'black_logo',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_5224818e39d04',
				'label' => 'Black Logo Base64',
				'name' => 'black_logo_base64',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_522480b139cfd',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5202e1c285791',
				'label' => 'Black Logo no Atkore',
				'name' => 'black_logo_no_atkore',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_522481c939d05',
				'label' => 'Black Logo no Atkore Base64',
				'name' => 'black_logo_no_atkore_base64',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_522480b139cfd',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_51ff1217b703a',
				'label' => 'Black Logo Horizontal',
				'name' => 'black_logo_horizontal',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_522481da39d06',
				'label' => 'Black Logo Horizontal Base64',
				'name' => 'black_logo_horizontal_base64',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_522480b139cfd',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_517f91abc86dd',
				'label' => 'Colors',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_22',
				'label' => 'Primary Color',
				'name' => 'primary_color',
				'type' => 'color_picker',
				'required' => 1,
				'default_value' => '#3F8223',
			),
			array (
				'key' => 'field_5202da071b28b',
				'label' => 'Secondary Color',
				'name' => 'secondary_color',
				'type' => 'color_picker',
				'default_value' => '',
			),
			array (
				'key' => 'field_24',
				'label' => 'Tertiary Color',
				'name' => 'tertiary_color',
				'type' => 'color_picker',
				'required' => 1,
				'default_value' => '#792918',
			),
			array (
				'key' => 'field_52248203983b8',
				'label' => 'Top Nav Color',
				'name' => 'top_nav_color',
				'type' => 'color_picker',
				'default_value' => '',
			),
			array (
				'key' => 'field_52248218983b9',
				'label' => 'Link Color',
				'name' => 'link_color',
				'type' => 'color_picker',
				'default_value' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-branding',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}
