<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_template-tabs',
		'title' => 'Template - Tabs',
		'fields' => array (
			array (
				'key' => 'field_tabs',
				'label' => 'Tabs',
				'name' => 'tabs',
				'type' => 'flexible_content',
				'layouts' => array (
					array (
						'label' => 'Normal Tab',
						'name' => 'normal_tab',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_normal_tab_label',
								'label' => 'Tab Label',
								'name' => 'tab_label',
								'type' => 'text',
								'column_width' => 10,
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_normal_tab_content',
								'label' => 'Tab Content',
								'name' => 'tab_content',
								'type' => 'wysiwyg',
								'column_width' => 90,
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
						),
					),
					array (
						'label' => 'Overview Tab',
						'name' => 'overview_tab',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_overview_tab_label',
								'label' => 'Tab Label',
								'name' => 'tab_label',
								'type' => 'text',
								'column_width' => 10,
								'default_value' => 'Overview',
								'placeholder' => 'Overview',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_overview_tab_content',
								'label' => 'Tab Content',
								'name' => 'tab_content',
								'type' => 'wysiwyg',
								'column_width' => 90,
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_overview_tab_image',
								'label' => 'Tab Image',
								'name' => 'tab_image',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'thumbnail',
								'library' => 'uploadedTo',
							),
						),
					),
					array (
						'label' => 'Specifications Tab',
						'name' => 'specifications_tab',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_specifications_tab_label',
								'label' => 'Tab Label',
								'name' => 'tab_label',
								'type' => 'text',
								'column_width' => 10,
								'default_value' => 'Specifications',
								'placeholder' => 'Specifications',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_specifications_tab_content',
								'label' => 'Tab Content',
								'name' => 'tab_content',
								'type' => 'wysiwyg',
								'column_width' => 90,
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_specifications_tab_image',
								'label' => 'Tab Image',
								'name' => 'tab_image',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
						),
					),
					array (
						'label' => 'Product Information Tab',
						'name' => 'product_information_tab',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_product_information_tab_label',
								'label' => 'Tab Label',
								'name' => 'tab_label',
								'type' => 'text',
								'column_width' => 10,
								'default_value' => 'Product Information',
								'placeholder' => 'Product Information',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_product_information_tab_content',
								'label' => 'Tab Content',
								'name' => 'tab_content',
								'type' => 'relationship',
								'column_width' => '',
								'return_format' => 'object',
								'post_type' => array (
									0 => 'tablepress_table',
								),
								'taxonomy' => array (
									0 => 'all',
								),
								'filters' => array (
									0 => 'search',
								),
								'result_elements' => array (
									0 => 'post_type',
									1 => 'post_title',
								),
								'max' => '',
							),
						),
					),
					array (
						'label' => 'PDF Tab',
						'name' => 'pdf_tab',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_pdf_tab_label',
								'label' => 'Tab Label',
								'name' => 'tab_label',
								'type' => 'text',
								'column_width' => 10,
								'default_value' => 'Veiw PDF',
								'placeholder' => 'Veiw PDF',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_pdf_tab_content',
								'label' => 'Tab Content',
								'name' => 'tab_content',
								'type' => 'ShortCode',
								'column_width' => '',
							),
						),
					),
					array (
						'label' => 'Tab with Sub Sections',
						'name' => 'tab_with_sub_sections',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_tab_with_sub_sections_label',
								'label' => 'Tab Label',
								'name' => 'tab_label',
								'type' => 'text',
								'column_width' => 10,
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_sub_sections',
								'label' => 'Sub Sections',
								'name' => 'sub_sections',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_sub_section_tab_label',
										'label' => 'Tab Label',
										'name' => 'tab_label',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'none',
										'maxlength' => '',
									),
									array (
										'key' => 'field_sub_section_tab_content',
										'label' => 'Tab Content',
										'name' => 'tab_content',
										'type' => 'wysiwyg',
										'column_width' => '',
										'default_value' => '',
										'toolbar' => 'full',
										'media_upload' => 'yes',
									),
								),
								'row_min' => 2,
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Sub Section',
							),
						),
					),
				),
				'button_label' => 'Add Tab',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'product',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-tabs.php',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'discussion',
				1 => 'comments',
				2 => 'revisions',
				3 => 'slug',
				4 => 'author',
				5 => 'format',
				6 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}
