<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_5841c75e2a9b5',
	'title' => 'Hero',
	'fields' => array (
		array (
			'key' => 'field_5841d163ad9b1',
			'label' => 'Crop',
			'name' => 'hero_crop',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Crop the desktop images to a normalized height specified in the theme.',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5841d407ad9b2',
			'label' => 'Slide',
			'name' => 'hero_slide',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5841d45cad9b4',
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Add Slide',
			'sub_fields' => array (
				array (
					'key' => 'field_5841d439ad9b3',
					'label' => 'Title',
					'name' => 'slide_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5841d45cad9b4',
					'label' => 'Image',
					'name' => 'slide_image',
					'type' => 'image_crop',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'crop_type' => 'min',
					'target_size' => 'thumbnail',
					'width' => '',
					'height' => '',
					'preview_size' => 'thumbnail',
					'force_crop' => 'no',
					'save_in_media_library' => 'no',
					'retina_mode' => 'no',
					'save_format' => 'url',
					'library' => 'all',
				),
				array (
					'key' => 'field_5841d4c0ad9b5',
					'label' => 'Overlay color',
					'name' => 'slide_overlay',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'light' => 'Light',
						'dark' => 'Dark',
					),
					'default_value' => array (
						0 => 'dark',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_5841d54dad9b6',
					'label' => 'Theme',
					'name' => 'slide_theme',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'boxed' => 'Boxed',
						'cover' => 'Cover',
					),
					'default_value' => array (
						0 => 'cover',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_5841d5a7ad9b7',
					'label' => 'Content',
					'name' => 'slide_content',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => 'wpautop',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array (
			array (
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'all',
			),
		),
	),
	'menu_order' => 99,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
