<?php

if ( !function_exists( 'shoestrap_compiler' ) ) :
/*
 * This function can be used to compile a less file to css using the lessphp compiler
 */
function shoestrap_compiler() {

  if ( shoestrap_getVariable( 'minimize_css', true ) == 1 )
    $options = array( 'compress'=>true );
  else
    $options = array( 'compress'=>false );

  $parser = new Less_Parser( $options );

  $parser->parse( shoestrap_complete_less() );

  $css = $parser->getCss();

  // Below are some really ugly hacks.
  $css = str_replace( get_template_directory() . '/assets/less/fonts/', '', $css );
  $css = str_replace( get_template_directory_uri() . '/assets/', '../', $css );
  $css = ( is_child_theme() ) ? str_replace( get_stylesheet_directory(), get_stylesheet_directory_uri(), $css ) : $css;

  return apply_filters( 'shoestrap_compiler_output', $css );
}
endif;


if ( !function_exists( 'shoestrap_compile_css' ) ) :
function shoestrap_compile_css( $method = 'php' ) {
  global $wp_filesystem;
  $file = shoestrap_css();
  
  // Initialize the Wordpress filesystem, no more using file_put_contents function
  if ( empty( $wp_filesystem ) ) {
    require_once( ABSPATH . '/wp-admin/includes/file.php' );
    WP_Filesystem();
  }

  $content = '/********* Do not edit this file *********/

';

  $content .= shoestrap_compiler();

  if ( is_writeable( $file ) || ( !file_exists( $file ) && is_writeable( dirname( $file ) ) ) ) {
    if ( !$wp_filesystem->put_contents( $file, $content, FS_CHMOD_FILE ) )
      return apply_filters( 'shoestrap_css_output', $content );
  }
}
endif;


if ( !function_exists( 'shoestrap_makecss' ) ) :
/*
 * Write the CSS to file
 */
function shoestrap_makecss() {
  shoestrap_compile_css();
}
endif;


if ( !function_exists( 'shoestrap_complete_less' ) ) :
/*
 * Brings all the LESS files that need to be compiled together.
 */
function shoestrap_complete_less() {
  $bootstrap    = get_template_directory() . '/assets/less/';

  $bootstrap_less = '@import "' . $bootstrap . 'app.less";';
  $bootstrap_less .= shoestrap_variables();

  if ( shoestrap_getVariable( 'gradients_toggle' ) == 1 )
    $bootstrap_less .= '@import "' . $bootstrap . 'gradients.less";';

  // The custom LESS file path
  $customlessfile = get_template_directory() . '/assets/less/custom.less';

  // If file is writable, process this.
  if ( is_writable( $customlessfile ) )
    $bootstrap_less .= '@import "' . $bootstrap . 'custom.less";';

  // Include the custom LESS code that users enter in the admin options.
  $bootstrap_less .= shoestrap_getVariable( 'user_less' );

  return apply_filters( 'shoestrap_compiler', $bootstrap_less );
}
endif;