<?php

// Do not edit this file.
// If you need to override this template you can use the 'shoestrap_content_single_override' hook.

while (have_posts()) : the_post(); ?>
  <article <?php post_class(); ?>>
    <?php do_action( 'shoestrap_in_article_top' ); ?>
    <header>
      <h1 class="entry-title"><?php the_title(); ?></h1>
      <?php
      // Override the entry-meta using the "shoestrap_entry_meta_override" hook
      // else load the default template for meta.
      if ( !has_action( 'shoestrap_entry_meta_override' ) )
        get_template_part('templates/entry-meta');
      else
        do_action( 'shoestrap_entry_meta_override' )
      ?>
    </header>
    <div class="entry-content">
      <?php do_action( 'shoestrap_single_pre_content' ); ?>
      <?php the_content(); ?>
      <div class="clearfix"></div>
      <?php do_action( 'shoestrap_single_after_content' ); ?>
    </div>
    <footer>
      <?php wp_link_pages(array('before' => '<nav class="page-nav"><p>' . __('Pages:', 'roots'), 'after' => '</p></nav>')); ?>
    </footer>
    <?php
    // The comments section loaded when appropriate
    if ( post_type_supports( 'post', 'comments' ) ):
      do_action( 'shoestrap_pre_comments' );
      if ( !has_action( 'shoestrap_comments_override' ) )
        comments_template('/templates/comments.php');
      else
        do_action( 'shoestrap_comments_override' );
      do_action( 'shoestrap_after_comments' );
    endif;
    ?>
    <?php do_action( 'shoestrap_in_article_bottom' ); ?>
  </article>
<?php endwhile;
