<?php

// Do not edit this file.
// If you need to override this template you can use the 'shoestrap_content_page_override' hook.
?>
<?php while (have_posts()) : the_post(); ?>
    <?php do_action( 'shoestrap_page_pre_content' ); ?>
    <?php the_content(); ?>
    <div class="clearfix"></div>
    <?php do_action( 'shoestrap_page_after_content' ); ?>
  <?php wp_link_pages(array('before' => '<nav class="pagination">', 'after' => '</nav>')); ?>
<?php endwhile;
