<?php

// Do not edit this file.
// If you need to override this template you can use the 'shoestrap_footer_override' hook.
?>
<footer class="content-info" role="contentinfo">
  <div class="<?php echo shoestrap_container_class(); ?>">
    <?php dynamic_sidebar('sidebar-footer'); ?>
    <p>&copy; <?php echo date('Y'); ?> <?php bloginfo('name'); ?></p>
  </div>
</footer>
