<?php

// Do not edit this file.
// If you need to override this template you can use the 'shoestrap_header_override' hook.
?>
<header class="banner navbar navbar-default <?php echo shoestrap_navbar_class(); ?>" role="banner">
  <div class="container">
    <?php if ( get_theme_mod( 'navbar_brand' ) != 0 ) :
      echo '<a class="navbar-brand ' . shoestrap_branding_class( false ) . '" href="' . home_url() . '/">';

      if ( get_theme_mod( 'navbar_logo' ) == 1 )
        shoestrap_logo();
      else
        bloginfo( 'name' );
      echo '</a>';
    endif; ?>
    <nav class="nav-main" role="navigation">
      <?php
        if ( has_nav_menu( 'primary_navigation' ) ) :
          wp_nav_menu( array( 'theme_location' => 'primary_navigation', 'menu_class' => 'nav nav-pills' ) );
        endif;
      ?>
    </nav>
  </div>
</header>
