<?php

// Do not edit this file.
// If you need to override this template you can use the 'shoestrap_header_override' hook.
?>
<header class="banner" role="banner">
  <div class="container">
    <nav class="nav-main" role="navigation">
      <?php
        if (has_nav_menu('primary_navigation')) :
          wp_nav_menu(array('theme_location' => 'primary_navigation', 'menu_class' => 'nav nav-pills'));
        endif;
      ?>
    </nav>
  </div>
</header>
