<?php

// Do not edit this file.
// If you need to override this template you can use the 'shoestrap_page_header_override' hook.
?>
<div class="page-header">
  <h1>
    <?php echo roots_title(); ?>
  </h1>
</div>
